import type { Metadata } from "next";
import { Poppins, JetBrains_Mono } from "next/font/google";
import "@/styles/globals.css";
// Import Swiper styles
import "swiper/css";
import { Providers } from "@/providers/proviers";

const geistSans = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const geistMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased  text-foreground relative`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
